applications/departamento/urls.py
from django.urls import path
from .views import *


app_name = "departamento_app"

urlpatterns = [
    path('añadir/', DepartamentoFormView.as_view(), name="añadir_departamento"),
    path('listar_departamento/', DepartamentoListView.as_view(), name="listar_departamentos"),
]

applications/empleados/urls.py
from django.urls import path
from .views import *


app_name = "empleados_app"

urlpatterns = [
    path('', InicioView.as_view(), name="inicio"),
    path('listar_empleados/', ListarEmpleados.as_view(), name="listar_empleados"),
    path('listar_area/<name>', ListarPorArea.as_view(), name="empleados_area"),
    path('listar_empleados_admin/', ListarEmpleadosAdmin.as_view(), name="listar_empleados_admin"),
    path('buscar_empleado/', ListarEmpleadosPorPalabraClave.as_view(),name="buscar_empleado"),
    path('listar_habilidades/<int:id>', ListarHabilidadesEmpleado.as_view()),
    path('detalle_empleado/<pk>', EmpleadoDetailView.as_view(), name="detalle_empleado"),
    path('crear_empleado/', EmpleadoCreateView.as_view(), name="crear_empleado"),
    path('success/', SuccessView.as_view(), name="correcto"),
    path('actualizar_empleado/<pk>', EmpleadoUpdateView.as_view(), name="actualizar_empleado"),
    path('eliminar_empleado/<pk>', EmpleadoDeleteView.as_view(), name="eliminar_empleado")
]

empleado/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary fondo">
    <div class="container-fluid">
      <a class="navbar-brand fs-3 fw-bold" href="#">
        <h1 class="text-primary fw-bolder ms-4">Employee</h1>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-5 text-center">
          <a class="nav-link" aria-current="page" href="{% url 'empleados_app:inicio' %}">Inicio</a>
          <a class="nav-link mx-3" href="{% url 'empleados_app:listar_empleados' %}">Buscar</a>
          <a class="nav-link mx-3" href="{% url 'departamento_app:listar_departamentos' %}">Departamento</a>
          <a class="nav-link mx-3" href="{% url 'empleados_app:listar_empleados_admin' %}">Administrar</a>
        </div>
        <div class="ms-auto">
          <a name="" id="" class="btn btn-success me-3" href="{% url 'departamento_app:añadir_departamento' %}" role="button">
            <i class="ti ti-user-plus me-2"></i>Agregar un departamento
          </a>
            <a name="" id="" class="btn btn-primary" href="{% url 'empleados_app:crear_empleado' %}" role="button">
              <i class="ti ti-user-plus me-2"></i>Agregar un empleado
            </a>
        </div>
      </div>
    </div>
</nav>