applications/departamento/urls.py
from django.urls import path
from .views import *


app_name = "departamento_app"

urlpatterns = [
    path('añadir/', DepartamentoFormView.as_view(), name="añadir_departamento"),
    path('listar_departamento/', DepartamentoListView.as_view(), name="listar_departamentos"),
]

applications/empleados/urls.py
from django.urls import path
from .views import *


app_name = "empleados_app"

urlpatterns = [
    path('', InicioView.as_view(), name="inicio"),
    path('listar_empleados/', ListarEmpleados.as_view(), name="listar_empleados"),
    path('listar_area/<name>', ListarPorArea.as_view(), name="empleados_area"),
    path('listar_empleados_admin/', ListarEmpleadosAdmin.as_view(), name="listar_empleados_admin"),
    path('buscar_empleado/', ListarEmpleadosPorPalabraClave.as_view(),name="buscar_empleado"),
    path('listar_habilidades/<int:id>', ListarHabilidadesEmpleado.as_view()),
    path('detalle_empleado/<pk>', EmpleadoDetailView.as_view(), name="detalle_empleado"),
    path('crear_empleado/', EmpleadoCreateView.as_view(), name="crear_empleado"),
    path('success/', SuccessView.as_view(), name="correcto"),
    path('actualizar_empleado/<pk>', EmpleadoUpdateView.as_view(), name="actualizar_empleado"),
    path('eliminar_empleado/<pk>', EmpleadoDeleteView.as_view(), name="eliminar_empleado")
]

empleado/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50, blank=True)
    shor_name = models.CharField('Nombre corto', max_length=20, unique=True)
    activo = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['id']
        unique_together = ('name', 'shor_name')

    def __str__(self):
        return f"{self.name} - {self.shor_name}"

applications/departamento/forms.py
from django import forms

class DepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    nombre_corto = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import *
from .forms import *
from applications.empleados.models import Empleado
from .models import Departamento

# Create your views here.

class DepartamentoListView(ListView):
    template_name = "departamento/listar_departamentos.html"
    model = Departamento
    context_object_name = 'departamentos'

class DepartamentoDetailView(DetailView):
    model = Departamento
    template_name = "departamento/detail.html"
    context_object_name = 'departamento'

class DepartamentoFormView(FormView):
    template_name = 'departamento/añadir.html'
    form_class = DepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        print('*********Estamos en el form valid*********')
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        depa = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['nombre_corto'],
            activo=True
        )
        depa.save()
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa
        )

        return super(DepartamentoFormView, self).form_valid(form)

templates/departamento/añadir.html
{% extends 'base/base.html' %} {% load crispy_forms_tags %} {% block body %} 

{% include 'includes/header.html' %}

<div class="container">
    <h1 class="text-center m-auto my-4 fw-bolder">Añadir Departamento</h1>
    <hr>
    <div class="card w-75 text-center m-auto p-5">
        <form method="POST">
            {% csrf_token %}
    
            <!-- Sección 1: Datos Generales -->
            <fieldset>
                <legend class="my-3 fw-bolder fs-7">Datos Generales</legend>
                {{ form.nombre|as_crispy_field }} 
                {{ form.apellidos|as_crispy_field}}
            </fieldset>
    
            <!-- Sección 2: Detalles del Departamento -->
            <fieldset>
                <legend class="my-3 fw-bolder fs-7">Detalles del Departamento</legend>
                {{ form.departamento|as_crispy_field}} 
                {{form.nombre_corto|as_crispy_field}}
            </fieldset>
            <button type="submit" class="btn btn-primary w-100">Registrar</button>
        </form>
    </div>

</div>
{% endblock body %}

templates/departamento/listar_departamentos.html
{% extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% block body %}
        {% include 'includes/header.html' %}
        <div class="container">
            <h1 class="fw-bolder my-4">Departamentos de la Empresa</h1>
            <hr class="mb-4">
            
            {% for dep in departamentos %}
            <div class="card text-start fw-75">
                <div class="row card-body">
                    <div class="col-4 text-sm">
                        <span class="fw-bolder me-3">Nombre:</span>{{dep.name}}
                    </div>
                    <div class="col-5 text-sm">
                        <span class="fw-bolder me-3">Identificador:</span>{{dep.shor_name}}
                    </div>
                    <div class="col-3 text-end">
                        <a name="" id="" class="btn btn-primary" href="{% url 'empleados_app:empleados_area' dep.name %}" role="button">
                            <i class="ti ti-users me-2"></i>Ver empleados
                        </a>
                    </div>
                </div>
              </div>
            {% endfor %}
            {% endblock body %}
        </body>
    </div>
</html>