applications/empleados/urls.py
from django.urls import path
from .views import *


app_name = "empleados_app"

urlpatterns = [
    path('', InicioView.as_view(), name="inicio"),
    path('listar_empleados/', ListarEmpleados.as_view(), name="listar_empleados"),
    path('listar_area/<name>', ListarPorArea.as_view(), name="empleados_area"),
    path('listar_empleados_admin/', ListarEmpleadosAdmin.as_view(), name="listar_empleados_admin"),
    path('buscar_empleado/', ListarEmpleadosPorPalabraClave.as_view(),name="buscar_empleado"),
    path('listar_habilidades/<int:id>', ListarHabilidadesEmpleado.as_view()),
    path('detalle_empleado/<pk>', EmpleadoDetailView.as_view(), name="detalle_empleado"),
    path('crear_empleado/', EmpleadoCreateView.as_view(), name="crear_empleado"),
    path('success/', SuccessView.as_view(), name="correcto"),
    path('actualizar_empleado/<pk>', EmpleadoUpdateView.as_view(), name="actualizar_empleado"),
    path('eliminar_empleado/<pk>', EmpleadoDeleteView.as_view(), name="eliminar_empleado")
]

empleado/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleados/models.py
from django.db import models
from applications.departamento.models import Departamento

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades empleados'
        ordering = ['id']

    def __str__(self):
        return f"{self.habilidad}"

class Empleado(models.Model):
    # Modelo para tabla empleado

    JOB_CHOICES = [
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro'),
    ]
    
    first_name = models.CharField('Nombre', max_length=50)
    last_name = models.CharField('Apellido', max_length=50)
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, verbose_name='Departamento')
    full_name = models.CharField('Nombre completo', max_length=120, blank=True)
    avatar = models.ImageField('Avatar', upload_to='empleado', blank=True, null=True)
    habilidad = models.ManyToManyField(Habilidades, verbose_name='Habilidades')

    class Meta:
        verbose_name = 'Mi empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['id']


    def __str__(self):
        return f"{self.id} | Nombre: {self.first_name} {self.last_name} | Departamento:  {self.departamento}"

applications/empleados/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Empleado
from django.views.generic import *
# Create your views here.


class InicioView(TemplateView):
    template_name = "inicio.html"

class ListarEmpleadosAdmin(ListView):
    template_name = 'empleado/listar_empleados_admin.html'
    paginate_by = 10
    context_object_name = 'lista_empleados'
    model = Empleado

class ListarEmpleados(ListView):
    template_name = 'empleado/listar_empleados.html'
    paginate_by = 4
    context_object_name = 'lista_empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword"," ")
        print("palabra_clave: ", palabra_clave)
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        print(lista)
        return lista

class ListarPorArea(ListView):
    template_name = 'empleado/listar_por_area.html'
    model = Empleado

    def get_queryset(self):
        area = self.kwargs['name']
        lista = Empleado.objects.filter(
            departamento__name=area
        )
        return lista
    context_object_name = 'lista_empleados'
    
class ListarEmpleadosPorPalabraClave(ListView):
    template_name='empleado/listar_empleados_clave.html'
    context_object_name = 'lista_empleados'


class ListarHabilidadesEmpleado(ListView):
    template_name = 'empleado/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        id_empleado = self.kwargs.get('id')
        empleado = Empleado.objects.get(id=id_empleado)
        return empleado.habilidad.all()
    

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "empleado/detalle_empleado.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "empleado/crear_empleado.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'avatar',
        'habilidad',
    ]
    success_url = reverse_lazy('empleados_app:listar_empleados_admin')

    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name = f"{empleado.first_name} {empleado.last_name}"
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)

class SuccessView(TemplateView):
    template_name = "empleado/vista_success.html"


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "empleado/actualizar_empleado.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidad',
    ]
    success_url = reverse_lazy('empleados_app:listar_empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)



class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "empleado/eliminar_empleado.html"
    success_url = reverse_lazy('empleados_app:correcto')
    




# 1. Listar todos los empleados de la empresa
# 2. Listar todos los empleados que pertenecen a un area de la empresa
# 3. Listar los empleados por trabajo
# 4. Listar los empleados por palabra clave
# 5. Listar habilidades de un empleado

templates/empleado/actualizar_empleado.html
{% extends 'base/base.html' %}

{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% block body %}
        {% include 'includes/header.html' %}
        <div class="container">
            <h1 class="fw-bolder my-4 text-center">Actualizar el Empleado</h1>
            <hr>
            <div class="card w-50 m-auto text-center p-5">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <p class="text-muted fs-2">Usar Ctrl-Click en computadores para seleccionar varias habilidades.</p>
                    <button type="submit" class="btn btn-primary">Actualizar</button>
                </form>
            </div>
        {% endblock body %}
        </body>
    </div>
</html>

templates/empleado/crear_empleado.html
{% extends 'base/base.html' %}

{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% block body %}
        {% include 'includes/header.html' %}
        <div class="container">
            <h1 class="fw-bolder my-4 text-center">Crear nuevo Empleado</h1>
            <hr>
            <div class="card w-50 m-auto text-center p-5">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <p class="text-muted fs-2">Usar Ctrl-Click en computadores para seleccionar varias habilidades.</p>
                    <button type="submit" class="btn btn-primary w-100 my-2">Añadir</button>
                </form>
            </div>
        {% endblock body %}
        </body>
    </div>
</html>

templates/empleado/detalle_empleado.html
{% extends 'base/base.html' %}
{% block body %}
{% include 'includes/header.html' %}
{% load static %}
<section class="w-100 p-4" style="background-color: #eee; border-radius: .5rem .5rem 0 0;">

    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item"><a href="{% url 'empleados_app:inicio' %}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{% url 'empleados_app:listar_empleados' %}">Buscar</a></li>
            <li class="breadcrumb-item active" aria-current="page">Empleado</li>
          </ol>
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="
            {% if empleado.avatar %}

            {{ empleado.avatar.url }} 
            
            {% else %} 

            {% static 'img/avatar.png' %}

            {% endif %}" alt="avatar" class="rounded-circle img-fluid ms-3" style="width: 240px; height: 240px;">
            <h3 class="my-4 fw-bolder">{{empleado.first_name}} {{empleado.last_name}}</h5>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
                <h2 class="fw-bolder mb-5 text-muted">Detalle Empleado</h2>
              <div class="col-sm-3">
                <p class="mb-0"><strong>Nombre Completo</strong></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{empleado.first_name}} {{empleado.last_name}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0"><strong>Area</strong></p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{empleado.departamento.name}}</p>
                </div>
              </div>
              <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><strong>Departamento</strong></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{empleado.departamento.shor_name}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><strong>Trabajo</strong></p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{empleado.get_job_display}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><strong>Habilidades</strong></p>
              </div>
              <div class="col-sm-9">
                <ul class="list-group">
                    {% for h in empleado.habilidad.all %}
                    <li class="list-group-item">{{ h.habilidad }}</li>
                    {% endfor %}
                </ul>
            </div>
            
            </div>
        </div>
{% endblock body %}
    

templates/empleado/eliminar_empleado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Eliminar Empleado</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Eliminar">
    </form>
</body>
</html>

templates/empleado/habilidades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Listar Habilidades</h1>
    <ul>
        {% for i in habilidades %}
            <li>{{i}}</li>
        {% endfor %}
</body>
</html>

templates/empleado/listar_empleados.html
{% extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% block body %}
        {% include 'includes/header.html' %}
        <div class="container">
            <h1 class="fw-bolder my-4">Busqueda de Empleados</h1>
            <hr class="mb-4">
            <div class="row">
                <form method="GET" action class="d-flex align-items-center">
                    {% csrf_token %}
                    <div class="input-group col-3">
                        <input type="text" name="kword" id="kword"
                            class="form-control w-50"
                            placeholder="Nombre del empleado">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary"style="margin-left: 10px;">
                                <i class="ti ti-user-search me-2"></i>Buscar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="row">
                <div class="table-responsive my-3">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Apellido</th>
                                <th scope="col">Departamento</th>
                                <th scope="col">Accion</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in lista_empleados %}
                            <tr>
                                <td>{{i.id}}</td>
                                <td>{{i.first_name}}</td>
                                <td>{{i.last_name}}</td>
                                <td>{{i.departamento}}</td>
                                <td><a
                                        href="{% url 'empleados_app:detalle_empleado' i.id %}">Ver</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if is_paginated %}
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            {% endif %}    
                            {% for page in paginator.page_range %}
                            <li class="page-item {% if page == page_obj.number %}active{% endif %}"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            {% endblock body %}
        </body>
    </div>
</html>

templates/empleado/listar_empleados_admin.html
{% extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% block body %}
        {% include 'includes/header.html' %}
        <div class="container">
            <h1 class="fw-bolder my-4">Listado de todos los empleados</h1>
            <hr class="mb-4">
            <div class="row">
                <div class="table-responsive my-3">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Apellido</th>
                                <th scope="col">Departamento</th>
                                <th scope="col">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for i in lista_empleados %}
                            <tr>
                                <td>{{i.id}}</td>
                                <td>{{i.first_name}}</td>
                                <td>{{i.last_name}}</td>
                                <td>{{i.departamento}}</td>
                                <td>
                                    <a class="btn btn-warning mx-1 mt-1" href="{% url 'empleados_app:actualizar_empleado' i.id %}" role="button">
                                        <i class="ti ti-pencil me-1"></i>Editar
                                    </a>
                                    <a class="btn btn-danger mx-1 mt-1" href="{% url 'empleados_app:eliminar_empleado' i.id %}" role="button">
                                        <i class="ti ti-trash me-1"></i>Eliminar
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if is_paginated %}
                    <nav aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            {% endif %}    
                            {% for page in paginator.page_range %}
                            <li class="page-item {% if page == page_obj.number %}active{% endif %}"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
            {% endblock body %}
        </body>
    </div>
</html>

templates/empleado/listar_empleados_clave.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        *{
            font-family: Helvetica, sans-serif;
        }
    </style>
</head>
<body>
    <form method="GET">
        {% csrf_token %}
        <input type="text" name="kword" id="kword" placeholder="Clave">
        <input type="submit" value="Buscar">
    </form>

    <ul>
        
        {% for i in lista_empleados  %}

            <li>{{ i.first_name }} {{ i.last_name }}</li>
            
        {% endfor %}
            
    </ul>

</body>
</html>

templates/empleado/listar_por_area.html
{% extends 'base/base.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {% block body %}
        {% include 'includes/header.html' %}
        <div class="container">
            <h1 class="fw-bolder my-4"> Empleados del Departamento </h1>
            <hr>
            <div class="row">
                <div class="card p-2">
                    <div class="table-responsive my-3">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Apellido</th>
                                    <th scope="col">Departamento</th>
                                    <th scope="col">Accion</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in lista_empleados %}
                                <tr>
                                    <td>{{i.first_name}}</td>
                                    <td>{{i.last_name}}</td>
                                    <td>{{i.departamento}}</td>
                                    <td><a
                                            href="{% url 'empleados_app:detalle_empleado' i.id %}">Ver</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                </div>
                
                </div>
        </div>
            {% endblock body %}
        </body>
    </div>
</html>

templates/empleado/vista_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Se guardo correctamente.</h1>
</body>
</html>